%% load piv
load("files/data/piv_u25mps_y1.5mm_x355-478mm_roughness_date20231214.mat")
% prepare data
data.vm = hypot(data.u,data.w);
data.vmm = squeeze(mean(data.vm,3));
data.vmr = squeeze(sqrt(var(data.vm,[],3)));
% compute criteria function
data.dwdl = prepinterm(data,type='dirgrad',prefilt='none',postfilt='median',postfiltker=[15,15],...
    fillmiss='none',padval={'symmetric','symmetric',false});
data.dwdlm = mean(data.dwdl,3);
%% show velocity variance
cellplot('contourf',data.x,data.z,data.vmr,axis='equal')
%% show velocity avegage
cellplot('contourf',data.x,data.z,data.vmm,axis='equal')
%% show velocty
cellplot('contourf',data.x,data.z,data.vm(:,:,1),axis='equal',...
    levels=linspace(0,50,25),clim=[20,50])
%% show criteria function
cellplot('contourf',data.x,data.z,data.dwdlm,axis='equal')
%% interactive probe statistics of criteria function
edges = linspace(0,1e-2)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funcpiv(edges,x),[1,2],data.x,data.z,data.vmm,...
    edges1,data.dwdl,draw='drawrectangle',axis={'square','auto'},...
    levels=linspace(0,50,25),rnumber=2)
function y = funcpiv(e,x)
    y = histcounts(x{:},e,'Normalization','pdf');
    disp([mean(x{1}(:)),var(x{1}(:))]);
end
%% interactive probe single PDF approximation of criteria function statistics
edges = linspace(0,1e-2)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funcpdfpiv1(edges,x),[1,2],data.x,data.z,data.vmm,...
    edges1,data.dwdl,draw='drawrectangle',axis={'square','auto'},...
    levels=linspace(0,40,25))
function y = funcpdfpiv1(e,x)
    disp([mean(x{1}(:)), var(x{1}(:))]);
    y0 = histcounts(x{1}(:),e,'Normalization','pdf');
    res = statdecom(e,x{1}(:),filtdim=1,kernel=nan,padval=false,...
        dist='gumbel', ...
        x0=[0.5,1,1],...
        mode=[1e-4, 7e-4],...
        var=[1e-09, 3e-8],...
        ans='struct',pass=2);
    disp(res.coef);
    disp(res.mparam);
    y = cat(2, y0', cell2mat(res.mpdf));
end
%% interactive probe double PDF approximation of criteria function statistics
edges = linspace(0,1e-2)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funcpdfpiv2(edges,x),[1,2],data.x,data.z,data.vmm,...
    edges1,data.dwdl,draw='drawrectangle',axis={'square','auto'},...
    levels=linspace(0,40,25),rinteraction='translate')
function y = funcpdfpiv2(e,x)
    disp([mean(x{1}(:)), var(x{1}(:))]);
    y0 = histcounts(x{1}(:),e,'Normalization','pdf');
    % beta
    % x0 = [0.73512, 0.00041316, 0.000173, 0.23057, 0.00080003, 0.00038017];
    % lb = [0, 5, 1e3, 0, 2, 1e3];
    % ub = [1, 2e1, 5e4, 1, 2e1, 5e4];
    % dist = {'beta', 'beta'};
    % gumbel
    x0 = [0.73512, 0.00041316, 0.000173, 0.23057, 0.00080003, 0.00038017];
    lb = [1e-2, 0, 0, 0, 0, 0];
    ub = [2, 7e-4, 5e-4, 2, 5e-3, 5e-3];
    dist = {'gumbel', 'gumbel'};    
    res = statdecom(e,x{1}(:),filtdim=1,kernel=nan,padval=false,...
        dist=dist,...
        x0=x0,...
        lb=lb,...
        ub=ub,...
        mode={[1e-4,7e-4],[9e-4,7e-3]},...
        var={[1e-09,3e-8],[]},...
        ans='struct',pass=2);
    disp(res.coef);
    disp(res.mparam);
    y = cat(2, y0', cell2mat(res.mpdf));
end
%% approximate criteria function statistics by gumbel
res = procstatdecom(edges, data.dwdl, kernel = [10,10,nan], stride = [4,4], ....
    padval = {'symmetric','symmetric',false}, ...
    dist = {'gumbel','gumbel'}, ...
    x0 = [0.73512, 0.00041316, 0.000173, 0.23057, 0.00080003, 0.00038017], ...
    lb = [1e-2, 0, 0, 0, 0, 0], ...
    ub = [2, 7e-4, 5e-4, 2, 5e-3, 5e-3], ...
    mode = {[1e-4,7e-4],[9e-4,7e-3]}, ...
    var = {[1e-09,3e-8],[]}, ...
    ans = 'struct', pass = 2, ...
    postfilt = 'median', postfiltker = [4,4]);
%% approximate criteria function statistics by beta
res = procstatdecom(edges, data.dwdl, kernel = [10,10,nan], stride = [4,4], ....
    padval = {'symmetric','symmetric',false}, ...
    dist = {'beta','beta'}, ...
    x0 = [0.73512, 0.00041316, 0.000173, 0.23057, 0.00080003, 0.00038017], ...
    lb = [0, 5, 1e3, 0, 2, 1e3], ...
    ub = [1, 2e1, 5e4, 1, 2e1, 5e4], ...
    mode = {[1e-4,7e-4],[9e-4,7e-3]}, ...
    var = {[1e-09,3e-8],[]}, ...
    ans = 'struct', pass = 2, ...
    prefilt = 'median', prefiltdim = [2,3], prefiltker = [3,3],...
    postfilt = 'median', postfiltker = [4,4]);
%% show intermittency computed by PDF integral ratio algorithm
cellplot('contourf',data.x,data.z,res.intermittency,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z, mm',clim=[0,1],...
    clabel='intermittency',subtitle='PDF integral ratio algorithm')
%% show threshold computed by CDF intersection algorithm
cellplot('contourf',data.x,data.z,res.threshold,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z_1, mm',cexponent=-3,...
    clabel='threshold',subtitle='CDF intersection algorithm')
%% show intermittency computed by CDF intersection algorithm
cellplot('contourf',data.x,data.z,res.mbinarized,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z_1, mm',clim=[0,1],...
    clabel='intermittency',subtitle='CDF intersection algorithm')
%%
%
%
%
%% load wire/xz-scan
load('files\data\cta_u25mps_x298-559mm_yvar_zvar_rough_date20240328.mat')
%% prepare data
data = prepcta(data, "refmarker", "n8", "storeraw", true);
data.raw = data.raw(:, :, :, 1);
data.z1 = data.z - min(data.z);
data.uvar = squeeze(var(data.raw,[],3));
%% compute criteria function
data.dudt = prepinterm(data,type='dt',postfilt='median',postfiltker=50);
%% interactive probe criteria function
cellprobe('contourf','plot',@(x)x{:},[2,3],data.x,data.z1,data.vm,...
    data.dudt,draw='drawpoint',axis={'square','auto'},...
    xlim={'auto',[1,512]},levels=linspace(0,40,25))
%% interactive probe statistics of criteria function
edges = linspace(0,50)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)func(edges,x),[2,3],data.x,data.z1,data.vm,...
    edges1,data.dudt,draw='drawpoint',axis={'square','auto'},...
    levels=linspace(0,40,25),rnumber=2)
function y = func(e,x)
    y = histcounts(x{:},e,'Normalization','pdf');
    disp([mean(x{1}),var(x{1})])
end
%% interactive probe single PDF approximation of criteria function statistics
edges = linspace(0,40)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funcpdf1(edges,x),[2,3],data.x,data.z1,data.uvar,...
    edges1,data.dudt,draw='drawpoint',axis={'square','auto'},...
    levels=linspace(0,40,25))
function y = funcpdf1(e,x)
    disp([mean(x{1}), var(x{1})]);
    y0 = histcounts(x{:},e,'Normalization','pdf');
    res = statdecom(e,x{1},filtdim=1,kernel=nan,padval=false,...
        dist='gumbel', ...
        x0=[0.5,1,1],...
        mode=[1,20],...
        ans='struct',pass=2);
    disp(res.coef);
    disp(res.mparam);
    y = cat(2, y0', cell2mat(res.mpdf));
end
%% interactive probe double PDF approximation of criteria function statistics
edges = linspace(0,40)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funcpdf2(edges,x),[2,3],data.x,data.z1,data.uvar,...
    edges1,data.dudt,draw='drawpoint',axis={'square','auto'},...
    levels=linspace(0,40,25))
function y = funcpdf2(e,x)
    disp([mean(x{1}), var(x{1})]);
    y0 = histcounts(x{:},e,'Normalization','pdf');
    res = statdecom(e,x{1},filtdim=1,kernel=nan,padval=false,...
        dist={'gumbel','gumbel'},...
        x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
        lb=[0.1,5,1,0.1,5,1],...
        ub=[2,20,20,2,25,10],...
        mode={[3,9],[10,20]},...
        var={[1,6],[20,100]},...
        ans='struct',pass=2);
    disp(res.coef);
    disp(res.mparam);
    y = cat(2, y0', cell2mat(res.mpdf));
end
%% interactive probe CDF approximation of criteria function statistics
edges = linspace(0,50)';
edges1 = edges(2:end)-diff(edges,1,1); 
cellprobe('contourf','plot',@(x)funccpdf(edges,x),[2,3],data.x,data.z1,data.vm,...
    edges1,data.dudt,draw='drawpoint',axis={'square','auto'},...
    levels=linspace(0,40,25))
function y = funccpdf(e,x)
    res = statdecom(e,x{1},filtdim=1,kernel=nan,padval=false,...
        dist={'gauss'},x0=[1,3,5],lb=[0.5,0,0],ub=[2,15,15],mode=[3,15],var=[1,10],ans='struct');
    y = res.mcdf{1};
end
%% approximate criteria function statistics
res = procstatdecom(edges,data.dudt,filtdim=1,kernel=nan,padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2);
%% approximate criteria function statistics
res = procstatdecom(edges,data.dudt,filtdim=1,kernel=nan,padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2,...
    postfilt='median',postfiltker=[4,4]);
%% approximate criteria function statistics
res = procstatdecom(edges,data.dudt,filtdim=1,kernel=nan,padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2,...
    postfilt={'gaussian','median'},postfiltker=[4,4]);
%% approximate criteria function statistics
res = procstatdecom(edges,data.dudt,filtdim=[1,2,3],kernel=[nan,2,2],padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2);
%% approximate criteria function statistics
res = procstatdecom(edges,permute(data.dudt,[2,1,3]),filtdim=[1,2,3],kernel=[2,nan,2],padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2);
%% approximate criteria function statistics
res = procstatdecom(edges,permute(data.dudt,[2,1,3]),filtdim=[1,2],kernel=[2,nan],padval=false,...
    dist={'gumbel','gumbel'},...
    x0=[0.5,5.4418,14.9996,0.8707,9.7976,1.7906],...
    lb=[0.1,5,1,0.1,5,1],...
    ub=[2,20,20,2,25,10],...
    mode={[3,9],[10,20]},...
    var={[1,6],[20,100]},...
    ans='struct',pass=2);
%% show intermittency computed by PDF integral ratio algorithm
cellplot('contourf',data.x,data.z1,res.intermittency,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z_1, mm',clim=[0,1],...
    clabel='intermittency',subtitle='PDF integral ratio algorithm')
%% show threshold computed by CDF intersection algorithm
cellplot('contourf',data.x,data.z1,res.threshold,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z_1, mm',clim=[0,1],...
    clabel='threshold',subtitle='CDF intersection algorithm')
%% show averaged binarized computed by CDF intersection algorithm
cellplot('contourf',data{i}.z,data{i}.y,res.mbinarized,axis='square',colorbar='on',...
    xlabel='x, mm',ylabel='z_1, mm',clim=[0,1],...
    clabel='averaged binarized',subtitle='CDF intersection algorithm')
%%